services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   # ✅ Esto es correcto
      MYSQL_DATABASE: ceraor
      MYSQL_USER: user  # ❌ NO USES root aquí
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

