<?php

use Phinx\Migration\AbstractMigration;

class CreateOrdersTable extends AbstractMigration
{
    public function change()
    {
        $table = $this->table('orders', ['id' => false, 'primary_key' => ['id']]);
        $table->addColumn('id', 'string', ['limit' => 255, 'null' => false])
              ->addColumn('folio_order', 'string', ['limit' => 20, 'null' => true])
              ->addColumn('patient', 'string', ['limit' => 100])
              ->addColumn('birthdate', 'date')
              ->addColumn('phone', 'string', ['limit' => 20])
              ->addColumn('doctor', 'string', ['limit' => 100])
              ->addColumn('address', 'string', ['limit' => 255])
              ->addColumn('professional_id', 'string', ['limit' => 100, 'null' => true])
              ->addColumn('email', 'string', ['limit' => 100, 'null' => true])
              ->addColumn('acetate_print', 'boolean', ['null' => true])
              ->addColumn('paper_print', 'boolean', ['null' => true])
              ->addColumn('send_email', 'boolean', ['null' => true])
              ->addColumn('packet', 'integer')
              ->addColumn('rx_panoramic', 'boolean', ['null' => true])
              ->addColumn('rx_arc_panoramic', 'boolean', ['null' => true])
              ->addColumn('rx_lateral_skull', 'boolean', ['null' => true])
              ->addColumn('ap_skull', 'boolean', ['null' => true])
              ->addColumn('pa_skull', 'boolean', ['null' => true])
              ->addColumn('paranasal_sinuses', 'boolean', ['null' => true])
              ->addColumn('atm_open_close', 'boolean', ['null' => true])
              ->addColumn('profilogram', 'boolean', ['null' => true])
              ->addColumn('watters_skull', 'boolean', ['null' => true])
              ->addColumn('palmar_digit', 'boolean', ['null' => true])
              ->addColumn('others_radiography', 'string', ['limit' => 255, 'null' => true])
              ->addColumn('occlusal_xray', 'boolean', ['null' => true])
              ->addColumn('superior', 'boolean', ['null' => true])
              ->addColumn('inferior', 'boolean', ['null' => true])
              ->addColumn('complete_periapical', 'boolean', ['null' => true])
              ->addColumn('individual_periapical', 'boolean', ['null' => true])
              ->addColumn('conductometry', 'boolean', ['null' => true])
              ->addColumn('clinical_photography', 'boolean', ['null' => true])
              ->addColumn('rickets', 'boolean', ['null' => true])
              ->addColumn('mcnamara', 'boolean', ['null' => true])
              ->addColumn('downs', 'boolean', ['null' => true])
              ->addColumn('jaraback', 'boolean', ['null' => true])
              ->addColumn('steiner', 'boolean', ['null' => true])
              ->addColumn('others_analysis', 'string', ['limit' => 255, 'null' => true])
              ->addColumn('analysis_bolton', 'boolean', ['null' => true])
              ->addColumn('analysis_moyers', 'boolean', ['null' => true])
              ->addColumn('others_models_analysis', 'string', ['limit' => 255, 'null' => true])
              ->addColumn('risina', 'boolean', ['null' => true])
              ->addColumn('dentalprint', 'boolean', ['null' => true])
              ->addColumn('3d_risina', 'boolean', ['null' => true])
              ->addColumn('surgical_guide', 'boolean', ['null' => true])
              ->addColumn('studio_piece', 'string', ['limit' => 100, 'null' => true])
              ->addColumn('complete_tomography', 'boolean', ['null' => true])
              ->addColumn('two_jaws_tomography', 'boolean', ['null' => true])
              ->addColumn('maxilar_tomography', 'boolean', ['null' => true])
              ->addColumn('jaw_tomography', 'boolean', ['null' => true])
              ->addColumn('snp_tomography', 'boolean', ['null' => true])
              ->addColumn('ear_tomography', 'boolean', ['null' => true])
              ->addColumn('atm_tomography_open_close', 'boolean', ['null' => true])
              ->addColumn('lateral_left_tomography_open_close', 'boolean', ['null' => true])
              ->addColumn('lateral_right_tomography_open_close', 'boolean', ['null' => true])
              ->addColumn('ondemand', 'string', ['limit' => 10, 'null' => true])
              ->addColumn('dicom', 'string', ['limit' => 10, 'null' => true])
              ->addColumn('tomography_piece', 'string', ['limit' => 10, 'null' => true])
              ->addColumn('implant', 'string', ['limit' => 10, 'null' => true])
              ->addColumn('impacted_tooth', 'string', ['limit' => 10, 'null' => true])
              ->addColumn('others_tomography', 'string', ['limit' => 100, 'null' => true])
              ->addColumn('stl', 'boolean', ['null' => true])
              ->addColumn('obj', 'boolean', ['null' => true])
              ->addColumn('ply', 'boolean', ['null' => true])
              ->addColumn('invisaligh', 'boolean', ['null' => true])
              ->addColumn('others_scanners', 'string', ['limit' => 255, 'null' => true])
              ->addColumn('maxilar_superior', 'boolean', ['null' => true])
              ->addColumn('maxilar_inferior', 'boolean', ['null' => true])
              ->addColumn('maxilar_both', 'boolean', ['null' => true])
              ->addColumn('maxilar_others', 'string', ['limit' => 255, 'null' => true])
              ->addColumn('dental_interpretation', 'string', ['limit' => 255, 'null' => true])
              ->addColumn('status', 'string', ['limit' => 20])
              ->addColumn('method', 'string', ['limit' => 20])
              ->addColumn('code_ticket', 'string', ['limit' => 20, 'null' => true])
              ->addColumn('active', 'integer')
              ->addColumn('created_at', 'date')
              ->addColumn('updated_at', 'date')
              ->create();
    }
}
